In [2]:
import torch

In [3]:
lst = [[1, 2], [3, 4]]; 

In [4]:
tensor = torch.tensor(lst);

In [5]:
print(tensor);

tensor([[1, 2],
        [3, 4]])


In [6]:
import numpy as np

In [7]:
np_array = np.array(lst);

In [8]:
np_tensor = torch.from_numpy(np_array);

In [9]:
print(np_tensor);

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [10]:
a = torch.tensor([1, 2, 3]);
b = torch.tensor([4, 5, 6]);

In [11]:
print(a + b);

tensor([5, 7, 9])


In [12]:
a.shape

torch.Size([3])

In [13]:
import torch.nn as nn

In [14]:
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32);
input_tensor.shape

torch.Size([2, 3])

In [15]:
linear_layer = nn.Linear(3, 2);

In [16]:
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [17]:
output = linear_layer(input_tensor);
output

tensor([[-1.3246, -1.2253],
        [-2.9577, -2.4265]], grad_fn=<AddmmBackward0>)

In [18]:
linear_layer.weight

Parameter containing:
tensor([[-0.1690, -0.2441, -0.1312],
        [-0.4329,  0.4014, -0.3689]], requires_grad=True)

In [19]:
linear_layer.bias

Parameter containing:
tensor([-0.2737, -0.4885], requires_grad=True)

In [20]:
modle = nn.Sequential(
    nn.Linear(5, 500),
    nn.Linear(500, 750),
    nn.Linear(750, 10)
)
modle

Sequential(
  (0): Linear(in_features=5, out_features=500, bias=True)
  (1): Linear(in_features=500, out_features=750, bias=True)
  (2): Linear(in_features=750, out_features=10, bias=True)
)

In [21]:
random_tensor0 = torch.tensor([[1,2,3,4,5]], dtype=torch.float32);
random_tensor0

tensor([[1., 2., 3., 4., 5.]])

In [22]:
output_tensor = modle(random_tensor0)

In [23]:
output_tensor

tensor([[-0.2320,  0.6357, -0.3994,  0.8172, -0.0513, -0.1936,  0.1315, -0.0031,
          0.1642,  0.8267]], grad_fn=<AddmmBackward0>)

In [24]:
input_tensor = torch.tensor([[1, 2, 3]]);

In [25]:
sigmoid = input_tensor.sigmoid();

In [26]:
sigmoid

tensor([[0.7311, 0.8808, 0.9526]])

In [27]:
model = nn.Sequential(
    nn.Linear(3, 1),
    nn.Linear(1, 3),
    nn.Linear(3, 1),
    nn.Sigmoid()
)

In [28]:
input_tensor = torch.tensor([[1, 2, 3]], dtype=torch.float32);

In [29]:
output = model(input_tensor);
output

tensor([[0.6613]], grad_fn=<SigmoidBackward0>)

In [30]:
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): Linear(in_features=1, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)


In [31]:
probabilities = nn.Softmax(dim=-1);
input_tensor = torch.tensor([[1.0, 2.0, 3.0]])


In [32]:
output_tensor = probabilities(input_tensor)

In [33]:
output_tensor

tensor([[0.0900, 0.2447, 0.6652]])

In [34]:
output_tensor.sum(dim=1)

tensor([1.])

In [35]:
input_data = torch.tensor([[1, 2, 3, 4, 5, 6], [22, 33, 44, 55, 66, 77], [3, 4, 5, 6, 7, 8], [12, 23, 34, 45, 56, 67], [19, 22, 41, 53, 101, 20]], dtype=torch.float32);

In [36]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1), 
    nn.Sigmoid()
); 

In [37]:
output = model(input_data)
output

tensor([[0.5408],
        [0.6104],
        [0.5145],
        [0.7266],
        [1.0000]], grad_fn=<SigmoidBackward0>)

In [38]:
number_of_classes = 3

In [39]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, number_of_classes),
    nn.Softmax(dim=-1)
)

In [40]:
output = model(input_data)
print(output.shape)

torch.Size([5, 3])


In [41]:
print(output)

tensor([[2.7113e-02, 8.4537e-01, 1.2752e-01],
        [2.2741e-18, 1.0000e+00, 5.5329e-08],
        [7.8609e-03, 8.9428e-01, 9.7863e-02],
        [1.4705e-15, 1.0000e+00, 2.7531e-07],
        [2.9777e-22, 1.0000e+00, 1.4366e-06]], grad_fn=<SoftmaxBackward0>)


In [42]:
sum = output.sum(dim=1)

In [43]:
sum

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [44]:
def find_closest_to_one_2d(tensor):
    # Calculate absolute difference from 1
    diff_from_one = torch.abs(tensor - 1.0)
    # Find index of minimum difference for each sample
    closest_indices = torch.argmin(diff_from_one, dim=1)
    # Get the actual values
    closest_values = torch.gather(tensor, 1, closest_indices.unsqueeze(1)).squeeze(1)
    return closest_indices, closest_values

In [45]:
find_closest_to_one_2d(output)

(tensor([1, 1, 1, 1, 1]),
 tensor([0.8454, 1.0000, 0.8943, 1.0000, 1.0000], grad_fn=<SqueezeBackward1>))

In [46]:
mammal = 0
bird = 1
reptile = 2


In [47]:
import torch.nn.functional as F

In [48]:
F.one_hot(torch.tensor(0), num_classes=3)

tensor([1, 0, 0])

In [49]:
from torch.nn import CrossEntropyLoss

In [50]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 3),
    nn.Linear(3, 2),    
    nn.Softmax(dim=1)
)

In [51]:
prediction = model(input_data)
prediction

tensor([[0.2526, 0.7474],
        [0.0052, 0.9948],
        [0.2152, 0.7848],
        [0.0147, 0.9853],
        [0.0828, 0.9172]], grad_fn=<SoftmaxBackward0>)

In [52]:
criterion = CrossEntropyLoss()
loss = criterion(prediction, torch.tensor([mammal, bird, mammal, bird, mammal]))
loss.backward()

In [53]:
model[0].weight.grad, model[0].bias.grad
model[1].weight.grad, model[1].bias.grad
model[2].weight.grad, model[2].bias.grad


(tensor([[-0.0033, -0.1310,  0.0755],
         [ 0.0033,  0.1310, -0.0755]]),
 tensor([-0.1091,  0.1091]))

In [54]:
import torch.optim as optim


In [55]:
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [56]:
optimizer


SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [57]:
optimizer.step()

In [58]:
def mean_squared_loss(pred, tgt):
    return np.mean((pred - tgt) ** 2)

In [59]:
criterion = nn.MSELoss()

In [60]:
data = torch.tensor([[0, 0, 0.5, 1, 0.036], [1, 0, 1, 2, 0.133], [2, 0, 0, 1, 0.234], [1, 0, 1, 0, 0.076], [2, 0, 1, 1, 0.170]])

In [61]:
data

tensor([[0.0000, 0.0000, 0.5000, 1.0000, 0.0360],
        [1.0000, 0.0000, 1.0000, 2.0000, 0.1330],
        [2.0000, 0.0000, 0.0000, 1.0000, 0.2340],
        [1.0000, 0.0000, 1.0000, 0.0000, 0.0760],
        [2.0000, 0.0000, 1.0000, 1.0000, 0.1700]])

In [62]:
features = torch.tensor(data[:, :-1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_24676\2638173784.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  features = torch.tensor(data[:, :-1])


In [63]:
features

tensor([[0.0000, 0.0000, 0.5000, 1.0000],
        [1.0000, 0.0000, 1.0000, 2.0000],
        [2.0000, 0.0000, 0.0000, 1.0000],
        [1.0000, 0.0000, 1.0000, 0.0000],
        [2.0000, 0.0000, 1.0000, 1.0000]])

In [64]:
targets = torch.tensor(data[:, -1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_24676\1945693325.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(data[:, -1])


In [65]:
targets

tensor([0.0360, 0.1330, 0.2340, 0.0760, 0.1700])

In [66]:
from torch.utils.data import TensorDataset, DataLoader

In [67]:
dataset = TensorDataset(features.float(), targets.float())

In [68]:
dataset

In [69]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [70]:
model = nn.Sequential(
    nn.Linear(4, 2),
    nn.Linear(2, 1)
)

In [71]:
criteria = nn.MSELoss()

In [72]:
optimizer = optim.SGD(model.parameters(), lr=0.001) 

In [73]:
num_epochs = 100

In [74]:
for epoch in range(num_epochs):
    for batch in dataloader:
        optimizer.zero_grad()
        features, targets = batch
        predictions = model(features)
        loss = criteria(predictions, targets)
        loss.backward()
        optimizer.step()

c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [75]:
mse = criterion

In [76]:
relu = nn.ReLU()

In [77]:
leaky_relu = nn.LeakyReLU(negative_slope=0.01)

In [78]:
total = 0
for param in model.parameters():
    total += param.numel()

total

13

In [79]:
sgd = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [80]:
layer = nn.Linear(10, 5)
nn.init.uniform_(layer.weight)
print(layer.weight.min())
print(layer.weight.max())

tensor(0.0416, grad_fn=<MinBackward1>)
tensor(0.9970, grad_fn=<MaxBackward1>)


In [81]:
import pandas as pd

In [82]:
animals = pd.read_csv('animals.csv')

In [83]:
animals

animal_name  hair  feathers  eggs  milk  predator  fins  legs  tail  type
0     skimmer     0         1     1     0         1     0     2     1     2
1        gull     0         1     1     0         1     0     2     1     2
2    seahorse     0         0     1     0         0     1     0     1     4
3     tuatara     0         0     1     0         1     0     4     1     3
4    squirrel     1         0     0     1         0     0     2     1     1

In [84]:
import numpy as np

In [85]:
features = animals.iloc[:, 1:-1]

In [86]:
X = features.to_numpy()

In [87]:
X

array([[0, 1, 1, 0, 1, 0, 2, 1],
       [0, 1, 1, 0, 1, 0, 2, 1],
       [0, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 4, 1],
       [1, 0, 0, 1, 0, 0, 2, 1]], dtype=int64)

In [88]:
target = animals.iloc[:, -1]

In [89]:
y = target.to_numpy()

In [90]:
from torch.utils.data import TensorDataset

In [91]:
dataset = TensorDataset(torch.tensor(X, dtype=torch.float32), torch.tensor(y, dtype=torch.float32))

In [92]:
sample = dataset[0]
input_sample, label_sample = sample


In [93]:
print('input sample:', input_sample)
print('label sample:', label_sample)


input sample: tensor([0., 1., 1., 0., 1., 0., 2., 1.])
label sample: tensor(2.)


In [94]:
from torch.utils.data import DataLoader

In [95]:
batch_size = 2
shuffle = True

In [96]:
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [97]:
for batch_inputs, batch_labels in dataloader:
    print('Batch inputs:', batch_inputs)
    print('Batch labels:', batch_labels)
    

Batch inputs: tensor([[0., 0., 1., 0., 0., 1., 0., 1.],
        [0., 1., 1., 0., 1., 0., 2., 1.]])
Batch labels: tensor([4., 2.])
Batch inputs: tensor([[0., 0., 1., 0., 1., 0., 4., 1.],
        [1., 0., 0., 1., 0., 0., 2., 1.]])
Batch labels: tensor([3., 1.])
Batch inputs: tensor([[0., 1., 1., 0., 1., 0., 2., 1.]])
Batch labels: tensor([2.])


In [98]:
training_loss = 0

In [99]:

validation_loss = 0

In [100]:
model.eval()

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

In [111]:
model = nn.Sequential(
    nn.Linear(16, 16),
    nn.ReLU(),
    nn.Dropout(p=0.5)
)




In [112]:
print(dataloader)

In [113]:
features, labels = next(iter(dataloader))

In [114]:
for i in range(1000):
    outputs = model(features)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x8 and 16x16)

In [109]:
features.shape

torch.Size([2, 8])

In [110]:
labels.shape

torch.Size([2])