In [1]:
import torch

In [2]:
lst = [[1, 2], [3, 4]]; 

In [3]:
tensor = torch.tensor(lst);

In [4]:
print(tensor);

tensor([[1, 2],
        [3, 4]])


In [5]:
import numpy as np

In [6]:
np_array = np.array(lst);

In [7]:
np_tensor = torch.from_numpy(np_array);

In [8]:
print(np_tensor);

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
a = torch.tensor([1, 2, 3]);
b = torch.tensor([4, 5, 6]);

In [10]:
print(a + b);

tensor([5, 7, 9])


In [11]:
a.shape

torch.Size([3])

In [12]:
import torch.nn as nn

In [13]:
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32);
input_tensor.shape

torch.Size([2, 3])

In [14]:
linear_layer = nn.Linear(3, 2);

In [15]:
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [16]:
output = linear_layer(input_tensor);
output

tensor([[-0.3808, -1.5938],
        [-1.0312, -3.3207]], grad_fn=<AddmmBackward0>)

In [17]:
linear_layer.weight

Parameter containing:
tensor([[ 0.0621,  0.1542, -0.4331],
        [-0.5136,  0.3590, -0.4210]], requires_grad=True)

In [18]:
linear_layer.bias

Parameter containing:
tensor([ 0.5480, -0.5351], requires_grad=True)

In [19]:
modle = nn.Sequential(
    nn.Linear(5, 500),
    nn.Linear(500, 750),
    nn.Linear(750, 10)
)
modle

Sequential(
  (0): Linear(in_features=5, out_features=500, bias=True)
  (1): Linear(in_features=500, out_features=750, bias=True)
  (2): Linear(in_features=750, out_features=10, bias=True)
)

In [20]:
random_tensor0 = torch.tensor([[1,2,3,4,5]], dtype=torch.float32);
random_tensor0

tensor([[1., 2., 3., 4., 5.]])

In [21]:
output_tensor = modle(random_tensor0)

In [22]:
output_tensor

tensor([[ 0.9840, -0.1873,  0.8550,  0.0510, -0.5834,  0.7001, -1.3258,  0.2018,
          0.2662, -0.0234]], grad_fn=<AddmmBackward0>)

In [23]:
input_tensor = torch.tensor([[1, 2, 3]]);

In [24]:
sigmoid = input_tensor.sigmoid();

In [25]:
sigmoid

tensor([[0.7311, 0.8808, 0.9526]])

In [26]:
model = nn.Sequential(
    nn.Linear(3, 1),
    nn.Linear(1, 3),
    nn.Linear(3, 1),
    nn.Sigmoid()
)

In [27]:
input_tensor = torch.tensor([[1, 2, 3]], dtype=torch.float32);

In [28]:
output = model(input_tensor);
output

tensor([[0.5806]], grad_fn=<SigmoidBackward0>)

In [29]:
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): Linear(in_features=1, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)


In [30]:
probabilities = nn.Softmax(dim=-1);
input_tensor = torch.tensor([[1.0, 2.0, 3.0]])


In [31]:
output_tensor = probabilities(input_tensor)

In [32]:
output_tensor

tensor([[0.0900, 0.2447, 0.6652]])

In [33]:
output_tensor.sum(dim=1)

tensor([1.])

In [34]:
input_data = torch.tensor([[1, 2, 3, 4, 5, 6], [22, 33, 44, 55, 66, 77], [3, 4, 5, 6, 7, 8], [12, 23, 34, 45, 56, 67], [19, 22, 41, 53, 101, 20]], dtype=torch.float32);

In [35]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1), 
    nn.Sigmoid()
); 

In [36]:
output = model(input_data)
output

tensor([[4.1016e-01],
        [7.8947e-03],
        [2.9408e-01],
        [9.3492e-02],
        [2.2699e-08]], grad_fn=<SigmoidBackward0>)

In [37]:
number_of_classes = 3

In [38]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, number_of_classes),
    nn.Softmax(dim=-1)
)

In [39]:
output = model(input_data)
print(output.shape)

torch.Size([5, 3])


In [40]:
print(output)

tensor([[5.6271e-01, 9.3776e-02, 3.4352e-01],
        [1.0000e+00, 4.6326e-10, 9.4285e-07],
        [6.5551e-01, 5.6734e-02, 2.8776e-01],
        [1.0000e+00, 1.2261e-08, 4.9033e-06],
        [1.0000e+00, 5.1347e-08, 1.7928e-06]], grad_fn=<SoftmaxBackward0>)


In [41]:
sum = output.sum(dim=1)

In [42]:
sum

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [43]:
def find_closest_to_one_2d(tensor):
    # Calculate absolute difference from 1
    diff_from_one = torch.abs(tensor - 1.0)
    # Find index of minimum difference for each sample
    closest_indices = torch.argmin(diff_from_one, dim=1)
    # Get the actual values
    closest_values = torch.gather(tensor, 1, closest_indices.unsqueeze(1)).squeeze(1)
    return closest_indices, closest_values

In [44]:
find_closest_to_one_2d(output)

(tensor([0, 0, 0, 0, 0]),
 tensor([0.5627, 1.0000, 0.6555, 1.0000, 1.0000], grad_fn=<SqueezeBackward1>))

In [45]:
mammal = 0
bird = 1
reptile = 2


In [46]:
import torch.nn.functional as F

In [47]:
F.one_hot(torch.tensor(0), num_classes=3)

tensor([1, 0, 0])

In [48]:
from torch.nn import CrossEntropyLoss

In [49]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 3),
    nn.Linear(3, 2),    
    nn.Softmax(dim=1)
)

In [50]:
prediction = model(input_data)
prediction

tensor([[0.5822, 0.4178],
        [0.9985, 0.0015],
        [0.6313, 0.3687],
        [0.9958, 0.0042],
        [0.9933, 0.0067]], grad_fn=<SoftmaxBackward0>)

In [51]:
criterion = CrossEntropyLoss()
loss = criterion(prediction, torch.tensor([mammal, bird, mammal, bird, mammal]))
loss.backward()

In [52]:
model[0].weight.grad, model[0].bias.grad
model[1].weight.grad, model[1].bias.grad
model[2].weight.grad, model[2].bias.grad


(tensor([[-0.1720, -0.0004, -0.1018],
         [ 0.1720,  0.0004,  0.1018]]),
 tensor([-0.0842,  0.0842]))

In [53]:
import torch.optim as optim


In [54]:
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [55]:
optimizer


SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [56]:
optimizer.step()

In [57]:
def mean_squared_loss(pred, tgt):
    return np.mean((pred - tgt) ** 2)

In [58]:
criterion = nn.MSELoss()

In [59]:
data = torch.tensor([[0, 0, 0.5, 1, 0.036], [1, 0, 1, 2, 0.133], [2, 0, 0, 1, 0.234], [1, 0, 1, 0, 0.076], [2, 0, 1, 1, 0.170]])

In [60]:
data

tensor([[0.0000, 0.0000, 0.5000, 1.0000, 0.0360],
        [1.0000, 0.0000, 1.0000, 2.0000, 0.1330],
        [2.0000, 0.0000, 0.0000, 1.0000, 0.2340],
        [1.0000, 0.0000, 1.0000, 0.0000, 0.0760],
        [2.0000, 0.0000, 1.0000, 1.0000, 0.1700]])

In [61]:
features = torch.tensor(data[:, :-1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_17460\2638173784.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  features = torch.tensor(data[:, :-1])


In [62]:
features

tensor([[0.0000, 0.0000, 0.5000, 1.0000],
        [1.0000, 0.0000, 1.0000, 2.0000],
        [2.0000, 0.0000, 0.0000, 1.0000],
        [1.0000, 0.0000, 1.0000, 0.0000],
        [2.0000, 0.0000, 1.0000, 1.0000]])

In [63]:
targets = torch.tensor(data[:, -1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_17460\1945693325.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(data[:, -1])


In [64]:
targets

tensor([0.0360, 0.1330, 0.2340, 0.0760, 0.1700])

In [65]:
from torch.utils.data import TensorDataset, DataLoader

In [66]:
dataset = TensorDataset(features.float(), targets.float())

In [67]:
dataset

In [68]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [69]:
model = nn.Sequential(
    nn.Linear(4, 2),
    nn.Linear(2, 1)
)

In [70]:
criteria = nn.MSELoss()

In [71]:
optimizer = optim.SGD(model.parameters(), lr=0.001) 

In [72]:
num_epochs = 100

In [73]:
for epoch in range(num_epochs):
    for batch in dataloader:
        optimizer.zero_grad()
        features, targets = batch
        predictions = model(features)
        loss = criteria(predictions, targets)
        loss.backward()
        optimizer.step()

c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [74]:
mse = criterion

In [75]:
relu = nn.ReLU()

In [76]:
leaky_relu = nn.LeakyReLU(negative_slope=0.01)

In [77]:
total = 0
for param in model.parameters():
    total += param.numel()

total

13

In [78]:
sgd = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [79]:
layer = nn.Linear(10, 5)
nn.init.uniform_(layer.weight)
print(layer.weight.min())
print(layer.weight.max())

tensor(0.0076, grad_fn=<MinBackward1>)
tensor(0.9528, grad_fn=<MaxBackward1>)


In [80]:
import pandas as pd

In [81]:
animals = pd.read_csv('animals.csv')

In [82]:
animals

animal_name  hair  feathers  eggs  milk  predator  fins  legs  tail  type
0     skimmer     0         1     1     0         1     0     2     1     2
1        gull     0         1     1     0         1     0     2     1     2
2    seahorse     0         0     1     0         0     1     0     1     4
3     tuatara     0         0     1     0         1     0     4     1     3
4    squirrel     1         0     0     1         0     0     2     1     1

In [83]:
import numpy as np

In [84]:
features = animals.iloc[:, 1:-1]

In [85]:
X = features.to_numpy()

In [86]:
X

array([[0, 1, 1, 0, 1, 0, 2, 1],
       [0, 1, 1, 0, 1, 0, 2, 1],
       [0, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 4, 1],
       [1, 0, 0, 1, 0, 0, 2, 1]], dtype=int64)

In [87]:
target = animals.iloc[:, -1]

In [88]:
y = target.to_numpy()

In [89]:
from torch.utils.data import TensorDataset

In [90]:
dataset = TensorDataset(torch.tensor(X, dtype=torch.float32), torch.tensor(y, dtype=torch.float32))

In [91]:
sample = dataset[0]
input_sample, label_sample = sample


In [92]:
print('input sample:', input_sample)
print('label sample:', label_sample)


input sample: tensor([0., 1., 1., 0., 1., 0., 2., 1.])
label sample: tensor(2.)


In [93]:
from torch.utils.data import DataLoader

In [94]:
batch_size = 2
shuffle = True

In [95]:
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [96]:
for batch_inputs, batch_labels in dataloader:
    print('Batch inputs:', batch_inputs)
    print('Batch labels:', batch_labels)
    

Batch inputs: tensor([[0., 1., 1., 0., 1., 0., 2., 1.],
        [0., 0., 1., 0., 0., 1., 0., 1.]])
Batch labels: tensor([2., 4.])
Batch inputs: tensor([[0., 1., 1., 0., 1., 0., 2., 1.],
        [0., 0., 1., 0., 1., 0., 4., 1.]])
Batch labels: tensor([2., 3.])
Batch inputs: tensor([[1., 0., 0., 1., 0., 0., 2., 1.]])
Batch labels: tensor([1.])


In [97]:
training_loss = 0

In [98]:

validation_loss = 0

In [99]:
model.eval()

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

In [100]:
model = nn.Sequential(
    nn.Linear(16, 16),
    nn.ReLU(),
    nn.Dropout(p=0.5)
)




In [101]:
print(dataloader)

In [102]:
features, labels = next(iter(dataloader))

In [2]:
%pip install kagglehub

  Using cached kagglehub-0.3.4-py3-none-any.whl.metadata (22 kB)
Using cached kagglehub-0.3.4-py3-none-any.whl (43 kB)
Note: you may need to restart the kernel to use updated packages.


    tinycss2 (>=1.1.0<1.2) ; extra == 'css'
             ~~~~~~~~^

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uom190346a/water-quality-and-potability")

print("Path to dataset files:", path)

100%|██████████| 251k/251k [00:00<00:00, 3.71MB/s]

Extracting files...
Path to dataset files: C:\Users\sbogu\.cache\kagglehub\datasets\uom190346a\water-quality-and-potability\versions\2


In [16]:
path

'C:\\Users\\sbogu\\.cache\\kagglehub\\datasets\\uom190346a\\water-quality-and-potability\\versions\\2'

In [25]:
from torch.utils.data import Dataset

class WaterDataset(Dataset):
    def __init__(self, path):
        super().__init__()
        df = pd.read_csv(path)
        self.data = df.to_numpy()

    def __len__(self):
        return self.data.shape[0]

    def __getitem__(self, idx):
        features = self.data[idx, :-1]
        label = self.data[idx, -1]
        return features, label

In [27]:
path = 'water_potability.csv'

In [32]:
dataset_train = WaterDataset(path)

In [33]:
from torch.utils.data import DataLoader

dataloader_train = DataLoader(
    dataset_train,
    batch_size=2,
    shuffle=True
)

In [35]:
features, labels = next(iter(dataloader_train))
print(f"Features: {features}, \nLabels: {labels}")

Features: tensor([[8.2788e+00, 2.0016e+02, 2.9382e+04, 7.2499e+00,        nan, 4.5647e+02,
         1.5161e+01, 7.0337e+01, 4.7677e+00],
        [8.9672e+00, 2.6648e+02, 3.4447e+04, 4.9096e+00,        nan, 3.4327e+02,
         1.4263e+01, 6.4960e+01, 3.7423e+00]], dtype=torch.float64), 
Labels: tensor([0., 1.], dtype=torch.float64)
