In [1]:
import torch

In [2]:
lst = [[1, 2], [3, 4]]; 

In [3]:
tensor = torch.tensor(lst);

In [4]:
print(tensor);

tensor([[1, 2],
        [3, 4]])


In [5]:
import numpy as np

In [6]:
np_array = np.array(lst);

In [7]:
np_tensor = torch.from_numpy(np_array);

In [8]:
print(np_tensor);

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
a = torch.tensor([1, 2, 3]);
b = torch.tensor([4, 5, 6]);

In [10]:
print(a + b);

tensor([5, 7, 9])


In [11]:
a.shape

torch.Size([3])

In [12]:
import torch.nn as nn

In [13]:
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32);
input_tensor.shape

torch.Size([2, 3])

In [14]:
linear_layer = nn.Linear(3, 2);

In [15]:
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [16]:
output = linear_layer(input_tensor);
output

tensor([[-0.7867, -0.4481],
        [-1.7370, -1.4681]], grad_fn=<AddmmBackward0>)

In [17]:
linear_layer.weight

Parameter containing:
tensor([[ 0.0172, -0.1720, -0.1620],
        [-0.1931, -0.0112, -0.1357]], requires_grad=True)

In [18]:
linear_layer.bias

Parameter containing:
tensor([0.0261, 0.1744], requires_grad=True)

In [19]:
modle = nn.Sequential(
    nn.Linear(5, 500),
    nn.Linear(500, 750),
    nn.Linear(750, 10)
)
modle

Sequential(
  (0): Linear(in_features=5, out_features=500, bias=True)
  (1): Linear(in_features=500, out_features=750, bias=True)
  (2): Linear(in_features=750, out_features=10, bias=True)
)

In [20]:
random_tensor0 = torch.tensor([[1,2,3,4,5]], dtype=torch.float32);
random_tensor0

tensor([[1., 2., 3., 4., 5.]])

In [21]:
output_tensor = modle(random_tensor0)

In [22]:
output_tensor

tensor([[ 0.4202, -0.1963,  0.2682,  0.2023, -0.9777,  0.5129,  0.3643,  0.8295,
         -0.0790, -0.5822]], grad_fn=<AddmmBackward0>)

In [23]:
input_tensor = torch.tensor([[1, 2, 3]]);

In [24]:
sigmoid = input_tensor.sigmoid();

In [25]:
sigmoid

tensor([[0.7311, 0.8808, 0.9526]])

In [26]:
model = nn.Sequential(
    nn.Linear(3, 1),
    nn.Linear(1, 3),
    nn.Linear(3, 1),
    nn.Sigmoid()
)

In [27]:
input_tensor = torch.tensor([[1, 2, 3]], dtype=torch.float32);

In [28]:
output = model(input_tensor);
output

tensor([[0.6536]], grad_fn=<SigmoidBackward0>)

In [29]:
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): Linear(in_features=1, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)


In [30]:
probabilities = nn.Softmax(dim=-1);
input_tensor = torch.tensor([[1.0, 2.0, 3.0]])


In [31]:
output_tensor = probabilities(input_tensor)

In [32]:
output_tensor

tensor([[0.0900, 0.2447, 0.6652]])

In [33]:
output_tensor.sum(dim=1)

tensor([1.])

In [34]:
input_data = torch.tensor([[1, 2, 3, 4, 5, 6], [22, 33, 44, 55, 66, 77], [3, 4, 5, 6, 7, 8], [12, 23, 34, 45, 56, 67], [19, 22, 41, 53, 101, 20]], dtype=torch.float32);

In [35]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1), 
    nn.Sigmoid()
); 

In [36]:
output = model(input_data)
output

tensor([[3.2684e-01],
        [2.0430e-06],
        [1.8955e-01],
        [7.8758e-05],
        [3.5736e-07]], grad_fn=<SigmoidBackward0>)

In [37]:
number_of_classes = 3

In [38]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, number_of_classes),
    nn.Softmax(dim=-1)
)

In [39]:
output = model(input_data)
print(output.shape)

torch.Size([5, 3])


In [40]:
print(output)

tensor([[1.2381e-02, 9.6284e-01, 2.4784e-02],
        [1.0055e-25, 1.0000e+00, 2.9529e-24],
        [1.3725e-03, 9.9577e-01, 2.8536e-03],
        [7.1066e-21, 1.0000e+00, 1.7263e-19],
        [2.9923e-24, 1.0000e+00, 5.1217e-21]], grad_fn=<SoftmaxBackward0>)


In [41]:
sum = output.sum(dim=1)

In [42]:
sum

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<SumBackward1>)

In [43]:
def find_closest_to_one_2d(tensor):
    # Calculate absolute difference from 1
    diff_from_one = torch.abs(tensor - 1.0)
    # Find index of minimum difference for each sample
    closest_indices = torch.argmin(diff_from_one, dim=1)
    # Get the actual values
    closest_values = torch.gather(tensor, 1, closest_indices.unsqueeze(1)).squeeze(1)
    return closest_indices, closest_values

In [44]:
find_closest_to_one_2d(output)

(tensor([1, 1, 1, 1, 1]),
 tensor([0.9628, 1.0000, 0.9958, 1.0000, 1.0000], grad_fn=<SqueezeBackward1>))

In [45]:
mammal = 0
bird = 1
reptile = 2


In [46]:
import torch.nn.functional as F

In [47]:
F.one_hot(torch.tensor(0), num_classes=3)

tensor([1, 0, 0])

In [48]:
from torch.nn import CrossEntropyLoss

In [58]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 3),
    nn.Linear(3, 2),    
    nn.Softmax(dim=1)
)

In [59]:
prediction = model(input_data)
prediction

tensor([[2.9390e-01, 7.0610e-01],
        [2.8241e-06, 1.0000e+00],
        [2.1176e-01, 7.8824e-01],
        [2.5215e-05, 9.9997e-01],
        [3.0770e-02, 9.6923e-01]], grad_fn=<SoftmaxBackward0>)

In [65]:
criterion = CrossEntropyLoss()
loss = criterion(prediction, torch.tensor([mammal, bird, mammal, bird, mammal]))
loss.backward()

In [66]:
model[0].weight.grad, model[0].bias.grad
model[1].weight.grad, model[1].bias.grad
model[2].weight.grad, model[2].bias.grad


(tensor([[-0.0173,  0.3127, -0.1072],
         [ 0.0173, -0.3127,  0.1072]]),
 tensor([-0.1013,  0.1013]))

In [67]:
import torch.optim as optim


In [68]:
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [69]:
optimizer


SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [70]:
optimizer.step()

In [71]:
def mean_squared_loss(pred, tgt):
    return np.mean((pred - tgt) ** 2)

In [72]:
criterion = nn.MSELoss()

In [74]:
data = torch.tensor([[0, 0, 0.5, 1, 0.036], [1, 0, 1, 2, 0.133], [2, 0, 0, 1, 0.234], [1, 0, 1, 0, 0.076], [2, 0, 1, 1, 0.170]])

In [75]:
data

tensor([[0.0000, 0.0000, 0.5000, 1.0000, 0.0360],
        [1.0000, 0.0000, 1.0000, 2.0000, 0.1330],
        [2.0000, 0.0000, 0.0000, 1.0000, 0.2340],
        [1.0000, 0.0000, 1.0000, 0.0000, 0.0760],
        [2.0000, 0.0000, 1.0000, 1.0000, 0.1700]])

In [77]:
features = torch.tensor(data[:, :-1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_17336\2638173784.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  features = torch.tensor(data[:, :-1])


In [78]:
features

tensor([[0.0000, 0.0000, 0.5000, 1.0000],
        [1.0000, 0.0000, 1.0000, 2.0000],
        [2.0000, 0.0000, 0.0000, 1.0000],
        [1.0000, 0.0000, 1.0000, 0.0000],
        [2.0000, 0.0000, 1.0000, 1.0000]])

In [81]:
targets = torch.tensor(data[:, -1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_17336\1945693325.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(data[:, -1])


In [82]:
targets

tensor([0.0360, 0.1330, 0.2340, 0.0760, 0.1700])

In [86]:
from torch.utils.data import TensorDataset, DataLoader

In [87]:
dataset = TensorDataset(features.float(), targets.float())

In [88]:
dataset

In [89]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [90]:
model = nn.Sequential(
    nn.Linear(4, 2),
    nn.Linear(2, 1)
)

In [91]:
criteria = nn.MSELoss()

In [92]:
optimizer = optim.SGD(model.parameters(), lr=0.001) 

In [93]:
num_epochs = 100

In [95]:
for epoch in range(num_epochs):
    for batch in dataloader:
        optimizer.zero_grad()
        features, targets = batch
        predictions = model(features)
        loss = criteria(predictions, targets)
        loss.backward()
        optimizer.step()

c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [ ]:
mse = criterion