In [1]:
import torch

In [2]:
lst = [[1, 2], [3, 4]]; 

In [3]:
tensor = torch.tensor(lst);

In [4]:
print(tensor);

tensor([[1, 2],
        [3, 4]])


In [5]:
import numpy as np

In [6]:
np_array = np.array(lst);

In [7]:
np_tensor = torch.from_numpy(np_array);

In [8]:
print(np_tensor);

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
a = torch.tensor([1, 2, 3]);
b = torch.tensor([4, 5, 6]);

In [10]:
print(a + b);

tensor([5, 7, 9])


In [11]:
a.shape

torch.Size([3])

In [12]:
import torch.nn as nn

In [13]:
input_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32);
input_tensor.shape

torch.Size([2, 3])

In [14]:
linear_layer = nn.Linear(3, 2);

In [15]:
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [16]:
output = linear_layer(input_tensor);
output

tensor([[-0.8173, -1.8009],
        [-0.9597, -4.5555]], grad_fn=<AddmmBackward0>)

In [17]:
linear_layer.weight

Parameter containing:
tensor([[-0.1948,  0.5469, -0.3995],
        [-0.1584, -0.3780, -0.3818]], requires_grad=True)

In [18]:
linear_layer.bias

Parameter containing:
tensor([-0.5178,  0.2590], requires_grad=True)

In [19]:
modle = nn.Sequential(
    nn.Linear(5, 500),
    nn.Linear(500, 750),
    nn.Linear(750, 10)
)
modle

Sequential(
  (0): Linear(in_features=5, out_features=500, bias=True)
  (1): Linear(in_features=500, out_features=750, bias=True)
  (2): Linear(in_features=750, out_features=10, bias=True)
)

In [20]:
random_tensor0 = torch.tensor([[1,2,3,4,5]], dtype=torch.float32);
random_tensor0

tensor([[1., 2., 3., 4., 5.]])

In [21]:
output_tensor = modle(random_tensor0)

In [22]:
output_tensor

tensor([[ 1.4206,  0.4426,  0.0721,  1.1126,  0.0271, -0.7675, -0.2410, -0.2283,
          0.1270,  0.0203]], grad_fn=<AddmmBackward0>)

In [23]:
input_tensor = torch.tensor([[1, 2, 3]]);

In [24]:
sigmoid = input_tensor.sigmoid();

In [25]:
sigmoid

tensor([[0.7311, 0.8808, 0.9526]])

In [26]:
model = nn.Sequential(
    nn.Linear(3, 1),
    nn.Linear(1, 3),
    nn.Linear(3, 1),
    nn.Sigmoid()
)

In [27]:
input_tensor = torch.tensor([[1, 2, 3]], dtype=torch.float32);

In [28]:
output = model(input_tensor);
output

tensor([[0.3527]], grad_fn=<SigmoidBackward0>)

In [29]:
print(model)

Sequential(
  (0): Linear(in_features=3, out_features=1, bias=True)
  (1): Linear(in_features=1, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)


In [30]:
probabilities = nn.Softmax(dim=-1);
input_tensor = torch.tensor([[1.0, 2.0, 3.0]])


In [31]:
output_tensor = probabilities(input_tensor)

In [32]:
output_tensor

tensor([[0.0900, 0.2447, 0.6652]])

In [33]:
output_tensor.sum(dim=1)

tensor([1.])

In [34]:
input_data = torch.tensor([[1, 2, 3, 4, 5, 6], [22, 33, 44, 55, 66, 77], [3, 4, 5, 6, 7, 8], [12, 23, 34, 45, 56, 67], [19, 22, 41, 53, 101, 20]], dtype=torch.float32);

In [35]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 1), 
    nn.Sigmoid()
); 

In [36]:
output = model(input_data)
output

tensor([[0.4820],
        [0.0229],
        [0.3588],
        [0.2292],
        [0.2409]], grad_fn=<SigmoidBackward0>)

In [37]:
number_of_classes = 3

In [38]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, number_of_classes),
    nn.Softmax(dim=-1)
)

In [39]:
output = model(input_data)
print(output.shape)

torch.Size([5, 3])


In [40]:
print(output)

tensor([[1.1069e-03, 1.1420e-01, 8.8469e-01],
        [3.6686e-42, 3.6668e-13, 1.0000e+00],
        [3.5782e-05, 6.5044e-02, 9.3492e-01],
        [1.3696e-34, 8.0628e-12, 1.0000e+00],
        [4.9363e-36, 3.4345e-15, 1.0000e+00]], grad_fn=<SoftmaxBackward0>)


In [41]:
sum = output.sum(dim=1)

In [42]:
sum

tensor([1., 1., 1., 1., 1.], grad_fn=<SumBackward1>)

In [43]:
def find_closest_to_one_2d(tensor):
    # Calculate absolute difference from 1
    diff_from_one = torch.abs(tensor - 1.0)
    # Find index of minimum difference for each sample
    closest_indices = torch.argmin(diff_from_one, dim=1)
    # Get the actual values
    closest_values = torch.gather(tensor, 1, closest_indices.unsqueeze(1)).squeeze(1)
    return closest_indices, closest_values

In [44]:
find_closest_to_one_2d(output)

(tensor([2, 2, 2, 2, 2]),
 tensor([0.8847, 1.0000, 0.9349, 1.0000, 1.0000], grad_fn=<SqueezeBackward1>))

In [45]:
mammal = 0
bird = 1
reptile = 2


In [46]:
import torch.nn.functional as F

In [47]:
F.one_hot(torch.tensor(0), num_classes=3)

tensor([1, 0, 0])

In [48]:
from torch.nn import CrossEntropyLoss

In [49]:
model = nn.Sequential(
    nn.Linear(6, 4),
    nn.Linear(4, 3),
    nn.Linear(3, 2),    
    nn.Softmax(dim=1)
)

In [50]:
prediction = model(input_data)
prediction

tensor([[3.2460e-01, 6.7540e-01],
        [5.1146e-02, 9.4885e-01],
        [2.6533e-01, 7.3467e-01],
        [1.8361e-01, 8.1639e-01],
        [8.4477e-06, 9.9999e-01]], grad_fn=<SoftmaxBackward0>)

In [51]:
criterion = CrossEntropyLoss()
loss = criterion(prediction, torch.tensor([mammal, bird, mammal, bird, mammal]))
loss.backward()

In [52]:
model[0].weight.grad, model[0].bias.grad
model[1].weight.grad, model[1].bias.grad
model[2].weight.grad, model[2].bias.grad


(tensor([[ 0.0136, -0.1537, -0.0516],
         [-0.0136,  0.1537,  0.0516]]),
 tensor([-0.0730,  0.0730]))

In [53]:
import torch.optim as optim


In [54]:
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [55]:
optimizer


SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [56]:
optimizer.step()

In [57]:
def mean_squared_loss(pred, tgt):
    return np.mean((pred - tgt) ** 2)

In [58]:
criterion = nn.MSELoss()

In [59]:
data = torch.tensor([[0, 0, 0.5, 1, 0.036], [1, 0, 1, 2, 0.133], [2, 0, 0, 1, 0.234], [1, 0, 1, 0, 0.076], [2, 0, 1, 1, 0.170]])

In [60]:
data

tensor([[0.0000, 0.0000, 0.5000, 1.0000, 0.0360],
        [1.0000, 0.0000, 1.0000, 2.0000, 0.1330],
        [2.0000, 0.0000, 0.0000, 1.0000, 0.2340],
        [1.0000, 0.0000, 1.0000, 0.0000, 0.0760],
        [2.0000, 0.0000, 1.0000, 1.0000, 0.1700]])

In [61]:
features = torch.tensor(data[:, :-1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_12808\2638173784.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  features = torch.tensor(data[:, :-1])


In [62]:
features

tensor([[0.0000, 0.0000, 0.5000, 1.0000],
        [1.0000, 0.0000, 1.0000, 2.0000],
        [2.0000, 0.0000, 0.0000, 1.0000],
        [1.0000, 0.0000, 1.0000, 0.0000],
        [2.0000, 0.0000, 1.0000, 1.0000]])

In [63]:
targets = torch.tensor(data[:, -1])

C:\Users\sbogu\AppData\Local\Temp\ipykernel_12808\1945693325.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(data[:, -1])


In [64]:
targets

tensor([0.0360, 0.1330, 0.2340, 0.0760, 0.1700])

In [65]:
from torch.utils.data import TensorDataset, DataLoader

In [66]:
dataset = TensorDataset(features.float(), targets.float())

In [67]:
dataset

In [68]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [69]:
model = nn.Sequential(
    nn.Linear(4, 2),
    nn.Linear(2, 1)
)

In [70]:
criteria = nn.MSELoss()

In [71]:
optimizer = optim.SGD(model.parameters(), lr=0.001) 

In [72]:
num_epochs = 100

In [73]:
for epoch in range(num_epochs):
    for batch in dataloader:
        optimizer.zero_grad()
        features, targets = batch
        predictions = model(features)
        loss = criteria(predictions, targets)
        loss.backward()
        optimizer.step()

c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
c:\Users\sbogu\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [74]:
mse = criterion

In [75]:
relu = nn.ReLU()

In [76]:
leaky_relu = nn.LeakyReLU(negative_slope=0.01)

In [77]:
total = 0
for param in model.parameters():
    total += param.numel()

total

13

In [78]:
sgd = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [79]:
layer = nn.Linear(10, 5)
nn.init.uniform_(layer.weight)
print(layer.weight.min())
print(layer.weight.max())

tensor(0.0931, grad_fn=<MinBackward1>)
tensor(0.9778, grad_fn=<MaxBackward1>)


In [81]:
import pandas as pd

In [84]:
animals = pd.read_csv('animals.csv')

In [85]:
animals

animal_name  hair  feathers  eggs  milk  predator  fins  legs  tail  type
0     skimmer     0         1     1     0         1     0     2     1     2
1        gull     0         1     1     0         1     0     2     1     2
2    seahorse     0         0     1     0         0     1     0     1     4
3     tuatara     0         0     1     0         1     0     4     1     3
4    squirrel     1         0     0     1         0     0     2     1     1

In [86]:
import numpy as np

In [87]:
features = animals.iloc[:, 1:-1]

In [88]:
X = features.to_numpy()

In [89]:
X

array([[0, 1, 1, 0, 1, 0, 2, 1],
       [0, 1, 1, 0, 1, 0, 2, 1],
       [0, 0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1, 0, 4, 1],
       [1, 0, 0, 1, 0, 0, 2, 1]], dtype=int64)

In [90]:
target = animals.iloc[:, -1]

In [93]:
y = target.to_numpy()

In [95]:
from torch.utils.data import TensorDataset

In [96]:
dataset = TensorDataset(torch.tensor(X, dtype=torch.float32), torch.tensor(y, dtype=torch.float32))

In [97]:
sample = dataset[0]
input_sample, label_sample = sample


In [98]:
print('input sample:', input_sample)
print('label sample:', label_sample)


input sample: tensor([0., 1., 1., 0., 1., 0., 2., 1.])
label sample: tensor(2.)


In [99]:
from torch.utils.data import DataLoader

In [100]:
batch_size = 2
shuffle = True

In [101]:
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=shuffle)

In [102]:
for batch_inputs, batch_labels in dataloader:
    print('Batch inputs:', batch_inputs)
    print('Batch labels:', batch_labels)
    

Batch inputs: tensor([[0., 1., 1., 0., 1., 0., 2., 1.],
        [1., 0., 0., 1., 0., 0., 2., 1.]])
Batch labels: tensor([2., 1.])
Batch inputs: tensor([[0., 1., 1., 0., 1., 0., 2., 1.],
        [0., 0., 1., 0., 1., 0., 4., 1.]])
Batch labels: tensor([2., 3.])
Batch inputs: tensor([[0., 0., 1., 0., 0., 1., 0., 1.]])
Batch labels: tensor([4.])


In [103]:
training_loss = 0

In [107]:

validation_loss = 0

In [109]:
model.eval()

Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)